### ISSUE TITLE
CUDA device fixed as 0 for the whitening layer

### ISSUE THREAD

**Issue by Ellenisawake** [roysubhankar/dwt-domain-adaptation#1]
In resnet50_dwt_mec_officehome.py line 524, cuda device fixed as 0.
In whitening.py line 23,24,48,51, cuda device fixed as 0.
This prohibits this code from running on non-"0" gpus.
Would be nice to make device id an argument.

**Comment by roysubhankar** [comment]
Can you please set CUDA_VISIBLE_DEVICES when you are running the code. This will let you run the code in any desired GPU you want.

**Comment by Ellenisawake** [comment]
> Can you please set CUDA_VISIBLE_DEVICES when you are running the code. This will let you run the code in any desired GPU you want.

Thanks.
